call pathogen#infect()
call pathogen#helptags()

autocmd FileType html,htmldjango,jinjahtml,eruby,mako let b:closetag_html_style=1
autocmd FileType html,xhtml,xml,htmldjango,jinjahtml,eruby,mako source ~/.vim/bundle/closetag/plugin/closetag.vim

set background=dark

"solarized color scheme config
let g:solarized_termtrans=1
let g:solarized_termcolors=256
let g:solarized_contrast="high"
let g:solarized_visibility="high"
colorscheme default

"command t config
let g:CommandTMaxFiles=50000

syntax on
filetype plugin on
set number
set t_Co=256
set hlsearch
set cursorline
filetype plugin on

"powerline related updates
set encoding=utf-8
set laststatus=2
set ts=2

"xmledit
au FileType xml setlocal foldmethod=syntax

if has("unix")
  let s:uname = system("uname")
  if s:uname == "Darwin\n"
    
    "powerline (only have it working for Mac so far)
    python from powerline.vim import setup as powerline_setup
    python powerline_setup()
    python del powerline_setup

    set rtp+={/Users/akilman/dotfiles/vim/bundle/powerline}/powerline/bindings/vim

    set guifont=Droid\ Sans\ Mono\ for\ Powerline
  endif
endif

set expandtab
set tabstop=4
set shiftwidth=4
